// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: daily_forecasts.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createDailyForecast = `-- name: CreateDailyForecast :one
INSERT INTO daily_forecasts (
    id,
    location_id,
    source_api,
    forecast_date,
    min_temp_c,
    max_temp_c,
    avg_temp_c,
    precipitation_mm,
    chance_of_rain_percent
)
VALUES (gen_random_uuid(), $1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, location_id, source_api, forecast_date, min_temp_c, max_temp_c, avg_temp_c, precipitation_mm, chance_of_rain_percent
`

type CreateDailyForecastParams struct {
	LocationID          uuid.UUID
	SourceApi           string
	ForecastDate        time.Time
	MinTempC            sql.NullFloat64
	MaxTempC            sql.NullFloat64
	AvgTempC            sql.NullFloat64
	PrecipitationMm     sql.NullFloat64
	ChanceOfRainPercent sql.NullInt32
}

func (q *Queries) CreateDailyForecast(ctx context.Context, arg CreateDailyForecastParams) (DailyForecast, error) {
	row := q.db.QueryRowContext(ctx, createDailyForecast,
		arg.LocationID,
		arg.SourceApi,
		arg.ForecastDate,
		arg.MinTempC,
		arg.MaxTempC,
		arg.AvgTempC,
		arg.PrecipitationMm,
		arg.ChanceOfRainPercent,
	)
	var i DailyForecast
	err := row.Scan(
		&i.ID,
		&i.LocationID,
		&i.SourceApi,
		&i.ForecastDate,
		&i.MinTempC,
		&i.MaxTempC,
		&i.AvgTempC,
		&i.PrecipitationMm,
		&i.ChanceOfRainPercent,
	)
	return i, err
}

const deleteAllDailyForecasts = `-- name: DeleteAllDailyForecasts :exec
DELETE FROM daily_forecasts
`

func (q *Queries) DeleteAllDailyForecasts(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllDailyForecasts)
	return err
}

const deleteDailyForecastsAtLocation = `-- name: DeleteDailyForecastsAtLocation :exec
DELETE FROM daily_forecasts WHERE location_id=$1
`

func (q *Queries) DeleteDailyForecastsAtLocation(ctx context.Context, locationID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteDailyForecastsAtLocation, locationID)
	return err
}

const deleteDailyForecastsAtLocationFromAPI = `-- name: DeleteDailyForecastsAtLocationFromAPI :exec
DELETE FROM daily_forecasts WHERE location_id=$1 AND source_api=$2
`

type DeleteDailyForecastsAtLocationFromAPIParams struct {
	LocationID uuid.UUID
	SourceApi  string
}

func (q *Queries) DeleteDailyForecastsAtLocationFromAPI(ctx context.Context, arg DeleteDailyForecastsAtLocationFromAPIParams) error {
	_, err := q.db.ExecContext(ctx, deleteDailyForecastsAtLocationFromAPI, arg.LocationID, arg.SourceApi)
	return err
}

const deleteDailyForecastsFromApi = `-- name: DeleteDailyForecastsFromApi :exec
DELETE FROM daily_forecasts WHERE source_api=$1
`

func (q *Queries) DeleteDailyForecastsFromApi(ctx context.Context, sourceApi string) error {
	_, err := q.db.ExecContext(ctx, deleteDailyForecastsFromApi, sourceApi)
	return err
}

const getDailyForecastAtLocationAndDate = `-- name: GetDailyForecastAtLocationAndDate :many
SELECT id, location_id, source_api, forecast_date, min_temp_c, max_temp_c, avg_temp_c, precipitation_mm, chance_of_rain_percent FROM daily_forecasts WHERE location_id=$1 AND forecast_date=$2
`

type GetDailyForecastAtLocationAndDateParams struct {
	LocationID   uuid.UUID
	ForecastDate time.Time
}

func (q *Queries) GetDailyForecastAtLocationAndDate(ctx context.Context, arg GetDailyForecastAtLocationAndDateParams) ([]DailyForecast, error) {
	rows, err := q.db.QueryContext(ctx, getDailyForecastAtLocationAndDate, arg.LocationID, arg.ForecastDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DailyForecast
	for rows.Next() {
		var i DailyForecast
		if err := rows.Scan(
			&i.ID,
			&i.LocationID,
			&i.SourceApi,
			&i.ForecastDate,
			&i.MinTempC,
			&i.MaxTempC,
			&i.AvgTempC,
			&i.PrecipitationMm,
			&i.ChanceOfRainPercent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDailyForecastAtLocationAndDateFromAPI = `-- name: GetDailyForecastAtLocationAndDateFromAPI :one
SELECT id, location_id, source_api, forecast_date, min_temp_c, max_temp_c, avg_temp_c, precipitation_mm, chance_of_rain_percent FROM daily_forecasts WHERE location_id=$1 AND forecast_date=$2 AND source_api=$3
`

type GetDailyForecastAtLocationAndDateFromAPIParams struct {
	LocationID   uuid.UUID
	ForecastDate time.Time
	SourceApi    string
}

func (q *Queries) GetDailyForecastAtLocationAndDateFromAPI(ctx context.Context, arg GetDailyForecastAtLocationAndDateFromAPIParams) (DailyForecast, error) {
	row := q.db.QueryRowContext(ctx, getDailyForecastAtLocationAndDateFromAPI, arg.LocationID, arg.ForecastDate, arg.SourceApi)
	var i DailyForecast
	err := row.Scan(
		&i.ID,
		&i.LocationID,
		&i.SourceApi,
		&i.ForecastDate,
		&i.MinTempC,
		&i.MaxTempC,
		&i.AvgTempC,
		&i.PrecipitationMm,
		&i.ChanceOfRainPercent,
	)
	return i, err
}

const updateDailyForecast = `-- name: UpdateDailyForecast :one
UPDATE daily_forecasts
SET forecast_date=$2, min_temp_c=$3, max_temp_c=$4, avg_temp_c=$5, precipitation_mm=$6, chance_of_rain_percent=$7
WHERE id=$1
RETURNING id, location_id, source_api, forecast_date, min_temp_c, max_temp_c, avg_temp_c, precipitation_mm, chance_of_rain_percent
`

type UpdateDailyForecastParams struct {
	ID                  uuid.UUID
	ForecastDate        time.Time
	MinTempC            sql.NullFloat64
	MaxTempC            sql.NullFloat64
	AvgTempC            sql.NullFloat64
	PrecipitationMm     sql.NullFloat64
	ChanceOfRainPercent sql.NullInt32
}

func (q *Queries) UpdateDailyForecast(ctx context.Context, arg UpdateDailyForecastParams) (DailyForecast, error) {
	row := q.db.QueryRowContext(ctx, updateDailyForecast,
		arg.ID,
		arg.ForecastDate,
		arg.MinTempC,
		arg.MaxTempC,
		arg.AvgTempC,
		arg.PrecipitationMm,
		arg.ChanceOfRainPercent,
	)
	var i DailyForecast
	err := row.Scan(
		&i.ID,
		&i.LocationID,
		&i.SourceApi,
		&i.ForecastDate,
		&i.MinTempC,
		&i.MaxTempC,
		&i.AvgTempC,
		&i.PrecipitationMm,
		&i.ChanceOfRainPercent,
	)
	return i, err
}
