// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type CurrentWeather struct {
	ID              uuid.UUID
	LocationID      uuid.UUID
	SourceApi       string
	UpdatedAt       time.Time
	TemperatureC    sql.NullFloat64
	Humidity        sql.NullInt32
	WindSpeedKmh    sql.NullFloat64
	PrecipitationMm sql.NullFloat64
	ConditionText   sql.NullString
}

type DailyForecast struct {
	ID                         uuid.UUID
	LocationID                 uuid.UUID
	SourceApi                  string
	ForecastDate               time.Time
	MinTempC                   sql.NullFloat64
	MaxTempC                   sql.NullFloat64
	AvgTempC                   sql.NullFloat64
	PrecipitationMm            sql.NullFloat64
	PrecipitationChancePercent sql.NullInt32
}

type HourlyForecast struct {
	ID                  uuid.UUID
	LocationID          uuid.UUID
	SourceApi           string
	ForecastDatetimeUtc time.Time
	TemperatureC        sql.NullFloat64
	Humidity            sql.NullInt32
	WindSpeedKmh        sql.NullFloat64
	PrecipitationMm     sql.NullFloat64
}

type Location struct {
	ID          uuid.UUID
	CityName    string
	Latitude    float64
	Longitude   float64
	CountryCode string
}
