package main

import (
	"database/sql"

	"github.com/cor0nius/willitrain/internal/database"
	"github.com/google/uuid"
)

// This file contains mapper functions responsible for converting data structures
// between the database layer and the business logic layer. The database models are
// auto-generated by sqlc and are tightly coupled to the database schema. The business
// logic models (defined in types.go) are designed for use within the application's
// core logic and API responses.
//
// This separation is a key architectural choice that decouples the application's
// core logic from the database schema. It allows the database schema to evolve
// without forcing changes in the business logic, and vice versa.

// databaseLocationToLocation maps a database model to a business logic model.
func databaseLocationToLocation(dbLocation database.Location) Location {
	return Location{
		LocationID:  dbLocation.ID,
		CityName:    dbLocation.CityName,
		Latitude:    dbLocation.Latitude,
		Longitude:   dbLocation.Longitude,
		CountryCode: dbLocation.CountryCode,
		Timezone:    dbLocation.Timezone.String,
	}
}

// locationToCreateLocationParams maps a business logic model to database create parameters.
func locationToCreateLocationParams(location Location) database.CreateLocationParams {
	return database.CreateLocationParams{
		CityName:    location.CityName,
		Latitude:    location.Latitude,
		Longitude:   location.Longitude,
		CountryCode: location.CountryCode,
	}
}

// databaseCurrentWeatherToCurrentWeather maps a database model to a business logic model.
func databaseCurrentWeatherToCurrentWeather(dbWeather database.CurrentWeather, location Location) CurrentWeather {
	return CurrentWeather{
		Location:      location,
		SourceAPI:     dbWeather.SourceApi,
		Timestamp:     dbWeather.UpdatedAt,
		Temperature:   dbWeather.TemperatureC.Float64,
		Humidity:      dbWeather.Humidity.Int32,
		WindSpeed:     dbWeather.WindSpeedKmh.Float64,
		Precipitation: dbWeather.PrecipitationMm.Float64,
		Condition:     dbWeather.ConditionText.String,
	}
}

// currentWeatherToCreateCurrentWeatherParams maps a business logic model to database create parameters.
func currentWeatherToCreateCurrentWeatherParams(weather CurrentWeather) database.CreateCurrentWeatherParams {
	return database.CreateCurrentWeatherParams{
		LocationID: weather.Location.LocationID,
		SourceApi:  weather.SourceAPI,
		UpdatedAt:  weather.Timestamp,
		TemperatureC: sql.NullFloat64{
			Float64: weather.Temperature,
			Valid:   true,
		},
		Humidity: sql.NullInt32{
			Int32: int32(weather.Humidity),
			Valid: true,
		},
		WindSpeedKmh: sql.NullFloat64{
			Float64: weather.WindSpeed,
			Valid:   true,
		},
		PrecipitationMm: sql.NullFloat64{
			Float64: weather.Precipitation,
			Valid:   true,
		},
		ConditionText: sql.NullString{
			String: weather.Condition,
			Valid:  true,
		},
	}
}

// currentWeatherToUpdateCurrentWeatherParams maps a business logic model to database update parameters.
func currentWeatherToUpdateCurrentWeatherParams(weather CurrentWeather, dbWeatherID uuid.UUID) database.UpdateCurrentWeatherParams {
	return database.UpdateCurrentWeatherParams{
		ID:        dbWeatherID,
		UpdatedAt: weather.Timestamp,
		TemperatureC: sql.NullFloat64{
			Float64: weather.Temperature,
			Valid:   true,
		},
		Humidity: sql.NullInt32{
			Int32: int32(weather.Humidity),
			Valid: true,
		},
		WindSpeedKmh: sql.NullFloat64{
			Float64: weather.WindSpeed,
			Valid:   true,
		},
		PrecipitationMm: sql.NullFloat64{
			Float64: weather.Precipitation,
			Valid:   true,
		},
		ConditionText: sql.NullString{
			String: weather.Condition,
			Valid:  true,
		},
	}
}

// databaseDailyForecastToDailyForecast maps a database model to a business logic model.
func databaseDailyForecastToDailyForecast(dbForecast database.DailyForecast, location Location) DailyForecast {
	return DailyForecast{
		Location:            location,
		SourceAPI:           dbForecast.SourceApi,
		Timestamp:           dbForecast.UpdatedAt,
		ForecastDate:        dbForecast.ForecastDate,
		MinTemp:             dbForecast.MinTempC.Float64,
		MaxTemp:             dbForecast.MaxTempC.Float64,
		Precipitation:       dbForecast.PrecipitationMm.Float64,
		PrecipitationChance: dbForecast.PrecipitationChancePercent.Int32,
		WindSpeed:           dbForecast.WindSpeedKmh.Float64,
		Humidity:            dbForecast.Humidity.Int32,
	}
}

// dailyForecastToCreateDailyForecastParams maps a business logic model to database create parameters.
func dailyForecastToCreateDailyForecastParams(forecast DailyForecast) database.CreateDailyForecastParams {
	return database.CreateDailyForecastParams{
		LocationID:   forecast.Location.LocationID,
		SourceApi:    forecast.SourceAPI,
		ForecastDate: forecast.ForecastDate,
		UpdatedAt:    forecast.Timestamp,
		MinTempC: sql.NullFloat64{
			Float64: forecast.MinTemp,
			Valid:   true,
		},
		MaxTempC: sql.NullFloat64{
			Float64: forecast.MaxTemp,
			Valid:   true,
		},
		PrecipitationMm: sql.NullFloat64{
			Float64: forecast.Precipitation,
			Valid:   true,
		},
		PrecipitationChancePercent: sql.NullInt32{
			Int32: int32(forecast.PrecipitationChance),
			Valid: true,
		},
		WindSpeedKmh: sql.NullFloat64{
			Float64: forecast.WindSpeed,
			Valid:   true,
		},
		Humidity: sql.NullInt32{
			Int32: int32(forecast.Humidity),
			Valid: true,
		},
	}
}

// dailyForecastToUpdateDailyForecastParams maps a business logic model to database update parameters.
func dailyForecastToUpdateDailyForecastParams(forecast DailyForecast, dbForecastID uuid.UUID) database.UpdateDailyForecastParams {
	return database.UpdateDailyForecastParams{
		ID:           dbForecastID,
		UpdatedAt:    forecast.Timestamp,
		ForecastDate: forecast.ForecastDate,
		MinTempC: sql.NullFloat64{
			Float64: forecast.MinTemp,
			Valid:   true,
		},
		MaxTempC: sql.NullFloat64{
			Float64: forecast.MaxTemp,
			Valid:   true,
		},
		PrecipitationMm: sql.NullFloat64{
			Float64: forecast.Precipitation,
			Valid:   true,
		},
		PrecipitationChancePercent: sql.NullInt32{
			Int32: int32(forecast.PrecipitationChance),
			Valid: true,
		},
		WindSpeedKmh: sql.NullFloat64{
			Float64: forecast.WindSpeed,
			Valid:   true,
		},
		Humidity: sql.NullInt32{
			Int32: int32(forecast.Humidity),
			Valid: true,
		},
	}
}

// databaseHourlyForecastToHourlyForecast maps a database model to a business logic model.
func databaseHourlyForecastToHourlyForecast(dbForecast database.HourlyForecast, location Location) HourlyForecast {
	return HourlyForecast{
		Location:            location,
		SourceAPI:           dbForecast.SourceApi,
		Timestamp:           dbForecast.UpdatedAt,
		ForecastDateTime:    dbForecast.ForecastDatetimeUtc,
		Temperature:         dbForecast.TemperatureC.Float64,
		Humidity:            dbForecast.Humidity.Int32,
		WindSpeed:           dbForecast.WindSpeedKmh.Float64,
		Precipitation:       dbForecast.PrecipitationMm.Float64,
		PrecipitationChance: dbForecast.PrecipitationChancePercent.Int32,
		Condition:           dbForecast.ConditionText.String,
	}
}

// hourlyForecastToCreateHourlyForecastParams maps a business logic model to database create parameters.
func hourlyForecastToCreateHourlyForecastParams(forecast HourlyForecast) database.CreateHourlyForecastParams {
	return database.CreateHourlyForecastParams{
		LocationID:          forecast.Location.LocationID,
		SourceApi:           forecast.SourceAPI,
		ForecastDatetimeUtc: forecast.ForecastDateTime,
		UpdatedAt:           forecast.Timestamp,
		TemperatureC: sql.NullFloat64{
			Float64: forecast.Temperature,
			Valid:   true,
		},
		Humidity: sql.NullInt32{
			Int32: int32(forecast.Humidity),
			Valid: true,
		},
		WindSpeedKmh: sql.NullFloat64{
			Float64: forecast.WindSpeed,
			Valid:   true,
		},
		PrecipitationMm: sql.NullFloat64{
			Float64: forecast.Precipitation,
			Valid:   true,
		},
		PrecipitationChancePercent: sql.NullInt32{
			Int32: int32(forecast.PrecipitationChance),
			Valid: true,
		},
		ConditionText: sql.NullString{
			String: forecast.Condition,
			Valid:  true,
		},
	}
}

// hourlyForecastToUpdateHourlyForecastParams maps a business logic model to database update parameters.
func hourlyForecastToUpdateHourlyForecastParams(forecast HourlyForecast, dbForecastID uuid.UUID) database.UpdateHourlyForecastParams {
	return database.UpdateHourlyForecastParams{
		ID:                  dbForecastID,
		UpdatedAt:           forecast.Timestamp,
		ForecastDatetimeUtc: forecast.ForecastDateTime,
		TemperatureC: sql.NullFloat64{
			Float64: forecast.Temperature,
			Valid:   true,
		},
		Humidity: sql.NullInt32{
			Int32: int32(forecast.Humidity),
			Valid: true,
		},
		WindSpeedKmh: sql.NullFloat64{
			Float64: forecast.WindSpeed,
			Valid:   true,
		},
		PrecipitationMm: sql.NullFloat64{
			Float64: forecast.Precipitation,
			Valid:   true,
		},
		PrecipitationChancePercent: sql.NullInt32{
			Int32: int32(forecast.PrecipitationChance),
			Valid: true,
		},
		ConditionText: sql.NullString{
			String: forecast.Condition,
			Valid:  true,
		},
	}
}
