version: '3.8'

services:
  willitrain:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - docker.env
    depends_on:
      migrator:
        condition: service_completed_successfully
      redis:
        condition: service_started

  migrator:
    image: golang:1.24.4-alpine
    working_dir: /app
    volumes:
      - .:/app
    env_file:
      - docker.env
    depends_on:
      postgres:
        condition: service_healthy
    command: sh -c "go install github.com/pressly/goose/v3/cmd/goose@latest && goose -dir ./sql/schema postgres $$DB_URL up"

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - docker.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus

volumes:
  postgres-data:
  prometheus-data: