name: Continuous Deployment

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: 'access_token'
          workload_identity_provider: 'projects/908739103426/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'willitrain-cd@willitrain-467605.iam.gserviceaccount.com'

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Login to Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: europe-west1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Build and Push Docker Image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: europe-west1-docker.pkg.dev/willitrain-467605/willitrain/willitrain:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Set up Go for Migrations
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'

      - name: Start Cloud SQL Proxy
        run: |
          wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O cloud_sql_proxy
          chmod +x cloud_sql_proxy
          ./cloud_sql_proxy -instances=willitrain-467605:europe-west1:willitrain-db=tcp:5432 & 

      - name: Run Database Migrations
        run: |
          unset PGUSER PGDATABASE PGHOST PGPORT PGPASSWORD
          go install github.com/pressly/goose/v3/cmd/goose@latest
          goose -dir ./sql/schema postgres "${{ secrets.DB_URL }}" up
        env:
          DB_URL: ${{ secrets.DB_URL }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: 'willitrain'
          region: 'europe-west1'
          image: europe-west1-docker.pkg.dev/willitrain-467605/willitrain/willitrain:${{ github.sha }}
          
          # Pass VPC connector and Cloud SQL instances as flags
          flags: |-
            --vpc-connector=willitrain-connector
            --add-cloudsql-instances=willitrain-467605:europe-west1:willitrain-db
            --verbosity=debug

          # Mount secrets as environment variables
          secrets: |-
            GMP_KEY=GMP_KEY:latest
            OWM_KEY=OWM_KEY:latest
            DB_URL=DB_URL:latest

          # Set environment variables
          env_vars: |-
            REDIS_URL=redis://10.19.20.155:6379
            GMP_GEOCODE_URL=https://maps.googleapis.com/maps/api/geocode/
            GMP_WEATHER_URL=https://weather.googleapis.com/v1/
            OWM_WEATHER_URL=https://api.openweathermap.org/data/3.0/onecall?
            OMETEO_WEATHER_URL=https://api.open-meteo.com/v1/forecast?
            CURRENT_INTERVAL_MIN=10
            HOURLY_INTERVAL_MIN=60
            DAILY_INTERVAL_MIN=720
